/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_kuncb_JinExternal */

#ifndef _Included_cn_kuncb_JinExternal
#define _Included_cn_kuncb_JinExternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_kuncb_JinExternal
 * Method:    kcInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_kuncb_JinExternal_kcInit
  (JNIEnv *, jclass);

/*
 * Class:     cn_kuncb_JinExternal
 * Method:    kcUninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_kuncb_JinExternal_kcUninit
  (JNIEnv *, jclass);

/*
 * Class:     cn_kuncb_JinExternal
 * Method:    kcUuid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_kuncb_JinExternal_kcUuid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
